variables:
  FIREBASE_CRASHLYTICS_COLLECTION_ENABLED:
    default: true
    type: boolean

platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        inject: |
          <meta-data android:name="firebase_performance_collection_enabled" android:value="$FIREBASE_CRASHLYTICS_COLLECTION_ENABLED" />
    gradle:
      - file: app/build.gradle
        target:
        insert: |
          apply plugin: com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin
          android {
              buildTypes {
                  debug {
                      // do not upload debug versions to crashlytics
                      firebaseCrashlytics {
                          mappingFileUploadEnabled false
                      }
                  }
              }
          }
  ios:
    plist:
      - replace: false
        entries:
          - FirebaseCrashlyticsCollectionEnabled: "$FIREBASE_CRASHLYTICS_COLLECTION_ENABLED"
    buildPhases:
      - comment: Crashlytics
        shellPath: "/bin/sh"
        shellScript: "\"${PODS_ROOT}/FirebaseCrashlytics/run\""
        inputPaths: ["\"$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)\""]
    
  